### ISSUE TITLE
parse-all-commits not working

### ISSUE THREAD

**Issue by tubbo** [HighwayThree/jira-extract-issue-keys#17]
I'm using this action in my workflow with the `parse-all-commits` option. Perhaps I'm not using it correctly, but I'm not able to get it working.

Here's my workflow output:

![Screen Shot 2021-07-26 at 2 32 13 PM](https://user-images.githubusercontent.com/113026/127040407-7a3a6701-e669-4cf7-85e7-68d13b654c8d.png)

It should be noted that _this_ commit which triggered the workflow does not have any Jira issue keys associated with it, but all other commits before it that have not been deployed yet do have their messages tagged with an issue. I thought/hoped `parse-all-commits` would look for everything since the last tagged release and try to parse out the issue keys from each message, but I might be mistaken.

**Comment by rhysv96** [comment]
I have the same same issue.

**Comment by orihomie** [comment]
Also, this options not works when I'm pushing a tag to a repo. But in my workflow I easily can read branch when I push tag, so thats seems to be a bug.
